externo: add nix-1p
nixosbrasil/onboard pull request #6
Opened 2022-01-15 14:16 UTC by lucasew

2022-01-16 18:06 UTC, bryanasdev000 requested changes
LGTM tirando o tic do `.` :P

2022-01-16 18:06 UTC, bryanasdev000 commented on src/externo/extra.md
> +Um guia bem direto ao ponto em inglês sobre conceitos básicos de Nix
Nitpicking, `.` no final da frase :P

2022-01-17 12:59 UTC, lucasew commented on src/externo/extra.md
> +Um guia bem direto ao ponto em inglês sobre conceitos básicos de Nix
Feito

2022-01-17 14:48 UTC, bryanasdev000 approved these changes

2022-01-17 14:49 UTC, bryanasdev000 approved these changes

2022-02-11 16:44 UTC, ratsclub approved these changes

2022-02-11 16:45 UTC, merged